version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: goldify_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql

  backend:
    build: ./goldify-server
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/goldify_db
      JWT_SECRET_KEY: super-secret
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    restart: always

  frontend:
    build: ./goldify-ui
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql-data:
